spring:
  application:
    name: xkck-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:50001/xkck?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: user
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
      time: HH:mm:ss

mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: seig.ljm.xkckserver.entity
    configuration:
      map-underscore-to-camel-case: true
      cache-enabled: false
      default-enum-type-handler: org.apache.ibatis.type.EnumTypeHandler
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    type-handlers-package: com.baomidou.mybatisplus.extension.handlers
    global-config:
      db-config:
        id-type: auto
        logic-delete-value: 1
        logic-not-delete-value: 0
      banner: false

redis:
  host: localhost
  port: 50007
  password: 123456
  database: 0
  timeout: 5000ms
  lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0

springdoc:
  api-docs:
    path: /v3/api-docs
    version: openapi_3_0
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha # 按字母顺序排序操作
    tagsSorter: alpha # 按字母顺序排序标签
    docExpansion: none # 默认展开状态
    version: 3.0.0
    enabled: true

# Logger Config
logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug
    org.springframework.integration.mqtt: debug

server:
  port: 8123

# MQTT Configuration
mqtt:
  broker:
    url: tcp://localhost:50005
  client:
    id: xkck-server
  username: admin
  password: public
  topics:
    - xkck/device/#

jwt:
  secret: "XKCK-LJM-SEIG-SECRET-KEY-2025-GRADUATION-PROJECT-SECURE-KEY-32BYTES"
  expiration: 86400000  # 24小时

